apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depolyment
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: 'sanjeevrisbud/wanderlust-frontend:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: workshop
spec:
  type: NodePort
  selector:
   role: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 31000
